[tools]
bun = "latest"
dotnet = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
java = "temurin"
maven = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
typst = "latest"
uv = "latest"
yarn = "latest"


[env]
ERL_AFLAGS="-kernel shell_history enabled"
_.path = [
    "~/.local/share/bin/"
]

[settings]
idiomatic_version_file_enable_tools = ["python"]
