[tools]
dotnet = "latest"
elixir = "1.18.4-otp-27"
erlang = "27"
go = "latest"
java = "temurin-21"
node = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"


[env]
ERL_AFLAGS="-kernel shell_history enabled"
_.path = [
    "~/.local/share/bin/"
]

[settings]
idiomatic_version_file_enable_tools = ["python"]
