tap "homebrew/bundle"
tap "libsql/sqld"
tap "tursodatabase/tap"
tap "oven-sh/bun"

brew "mas"
brew "composer"
brew "ffmpeg"
brew "gh"
brew "luarocks"
brew "neovim"
brew "pngpaste"
brew "websocat"
brew "tursodatabase/tap/turso"
brew "ripgrep"
brew "fzf"
brew "eza"
brew "zoxide"
brew "node"
brew "starship"
brew "lazygit"
brew "go"
brew "zsh-syntax-highlighting"
brew "tmux"
brew "opam"
brew "flyctl"
brew "zsh-autosuggestions"

cask "orbstack"
cask "wezterm"
cask "iina"
cask "pdf-expert"
cask "spotify"
cask "shottr"
cask "arc"
cask "alfred"
cask "font-meslo-lg-nerd-font"
cask "font-hack"
cask "font-fira-code"
cask "font-jetbrains-mono"

mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
