tap "homebrew/bundle"
tap "libsql/sqld"
tap "tursodatabase/tap"
tap "nikitabobko/tap"
tap "xwmx/taps"

brew "mas"
# brew "ffmpeg"
brew "gh"
# brew "luarocks"
brew "neovim"
brew "pngpaste"
brew "websocat"
brew "tursodatabase/tap/turso"
brew "ripgrep"
brew "fzf"
brew "eza"
brew "zoxide"
brew "node"
brew "starship"
brew "lazygit"
brew "go"
brew "zsh-syntax-highlighting"
brew "tmux"
brew "flyctl"
brew "zsh-autosuggestions"
brew "zig"
brew "nb"
brew "pandoc"
brew "wget"
brew "uv"
brew "caddy"
brew "stow"
brew "sesh"

cask "nikitabobko/tap/aerospace"
cask "orbstack"
cask "wezterm@nightly"
cask "iina"
cask "pdf-expert"
cask "spotify"
cask "shottr"
cask "arc"
cask "alfred"
cask "font-meslo-lg-nerd-font"
cask "font-hack"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "basictex"
cask "zotero"
cask "gimp"
cask "anki"
cask "kitty"

### mas "Microsoft Word", id: 462054704
### mas "Microsoft Excel", id: 462058435
### mas "Microsoft PowerPoint", id: 462062816
