[[search_dirs]]
path = "/Users/zihanjin/go/src"
depth = 1

[[search_dirs]]
path = "/Users/zihanjin/code"
depth = 1


[[search_dirs]]
path = "/Users/zihanjin/dotfiles/"
depth = 1


[[search_dirs]]
path = "/Users/zihanjin/.nb/"
depth = 1
