# --- Aliases ---
alias ls='eza --icons always'
alias tree='eza --icons always --tree'
alias tt='touch'
alias c='clear'
alias q='exit'
alias lg='lazygit'
alias vim='nvim'
alias nvi='nvim'
alias nv='nvim'
alias nvm='nvim'
alias tm='tmux -2'
alias cat='bat'
alias r='ranger'

# Function Aliases
alias rc='ranger_cd'
alias rs='ranger_sesh'
alias ff='open_in_nvim'
alias nr='open_in_nvim_rg'
